### PR TITLE
feat: add click away dismiss Popable

### PR DESCRIPTION
**Pull request by eveningkid**
Related to #7.

### CODE REVIEW

**Comment by nandorojo** [comment]
FWIW, I use this in my app for detecting clicking away from a `View`:

```ts

import { MutableRefObject, useEffect } from 'react'

const useClickAway = (
  ref: MutableRefObject<HTMLElement | null>,
  handler: (event: Event) => void
) => {
  useEffect(() => {
    const callback = (event: Event) => {
      const el = ref.current
      if (!event || !el || el.contains((event as any).target)) return
      handler(event)
    }

    document.addEventListener('click', callback)
    return () => document.removeEventListener('click', callback)
  }, [ref, handler])
}

export default useClickAway
```

Then:

```ts
useClickAway(viewRef, () => closeMenu())
```

**Comment by nandorojo** [comment]
This looks good, it should probably wrap 

```js
if (Platform.OS === 'web') 
```

For the click hander

**Comment by eveningkid** [comment]
Ok, so :)

- it now dismisses the popover on both native (using `Modal`) and web (using `document` listener)
- it defaults to "press" on native when `action` is "hover"

**Comment by nandorojo** [comment]
Nice!

One issue with the backdrop implementation here for native: the modal covers the content that pops over, as well as the target. This means that you can't make popover menus, since touches are absorbed by the modal overlay.

To support menus with a modal implementation, we'd have to clone the trigger, measure it, put it in the modal on top of itself. In other words, the popover and its trigger would need to be children of the modal, which is why a Portal came to mind for me originally.

You might already know this, so if you do, feel free to ignore my comment.

One example I saw of this is here: https://github.com/enesozturk/react-native-hold-menu

I also tried making this concept myself once with a portal: https://gist.github.com/nandorojo/b2053021239f10d5c609362a04be6a20

**Pull request merged**
